# Configuration Nixpacks pour forcer un build propre
# Pas de phase setup custom car npm n'est pas encore disponible

[phases.install]
cmds = ["rm -rf node_modules", "npm install"]

[phases.build]
cmds = ["rm -rf dist", "npm run build"]
